language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm-nightly
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = '7.1' ] ; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi;
