language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml

after_script:
  - if [ "$TRAVIS_PHP_VERSION" = '5.6' ] ; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi;
